language: bash
sudo: required
services:
    - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker tag Dockerfile jeykow/training
  - docker push jeykow/training
